### PR TITLE
Added inventory.js code, selling is not included

### PR DESCRIPTION
**Pull request by BadPythonCoder**
I have implemented the core inventory code but i have not implemented it into the index.js
If you really reallly really really REAALLYYY dont want to implement it yourself, then i guess i can do it but it is highly recommended that you do it yourself.

just require inventory.js like `const { Inventory } = require("./inventory.js");`

Inventory.js is a class, to get the inventory of a player just do `new Inventory(ID_OF_THE_USER_GOES_HERE);`

The inventory.js has a couple of methods:
- getMoney() -> returns int (money)
- getItems() -> returns array of item id's (of rods)
- buy(itemID) -> return string, either "bought" or "insufficient funds"

**ALSO CHANGE THE PATHS INSIDE INVENTORY.JS SO THAT IT WORKS ON WINDOWS**

### CODE REVIEW

**Comment by TheRedBlueCube3** [comment]
ok

**Comment by BadPythonCoder** [comment]
Should selling be added?

**Comment by TheRedBlueCube3** [comment]
nah i will make it myself, just make a removeItem method so i can remove it somehow
selling will just give you the money and remove the item so you can do that

**Comment by BadPythonCoder** [comment]
i already made a buy method which handles the money too, i am afraid that there might be database conflicts
so i think i should still add the sell myself

**Comment by TheRedBlueCube3** [comment]
fine do it yourself

**Comment by BadPythonCoder** [comment]
Alright done:

- sell(item_id) -> string, "item_not_present" if item doesnt exist and "sold" if sold
- add_money(money) -> nothing, adds... more money

i forgot to make it add the money in sell method so i am just gonna let you do that

**Comment by BadPythonCoder** [comment]
alright im gonna close this now

**Comment by BadPythonCoder** [comment]
wait first merge it
and then im gonna close it

**Comment by BadPythonCoder** [comment]
nvm closes automatically

**Pull request merged**
